#LEAN SIX SIGMA PROJECT

#This is time in days
#c(time for bus lisence, time for massage lisense, time for crimes)
Florida <- c(30, 60, 40)
Texas <- c(2, 5, 12)
California <- c(3, 5, 40)
DC <- c(4, 5, 20)
buslisence <- c(Florida[1], Texas[1], California[1], DC[1])
masslisence <- c(Florida[2], Texas[2], California[2], DC[2])
crimes <- c(Florida[3], Texas[3], California[3], DC[3])
variables <- c("Business Lisence", "Massage Lisence", "Crimes")
datamass <- cbind(buslisence, masslisence, crimes)
states <-c("Florida", "Texas", "California", "DC")
barplot(datamass,names=variables,beside=T, col= c("yellow", "orange", "red", "pink"), ylab = "Time till Data Collection Complete")+ legend(x=7.5, y= 60, states, col= c("yellow", "orange", "red", "pink"), lty=c(1,1))

variablestouse <- c("Business Lisence", "Business Lisence", "Business Lisence", "Business Lisence", "Massage Lisence", "Massage Lisence", "Massage Lisence", "Massage Lisence", "Crimes", "Crimes", "Crimes", "Crimes")
times <- c("30", "2", "3", "4", "60", "5", "5", "5", "40", "12", "40", "20")
state <- (c("Florida", "Texas", "California", "D.C.", "Florida", "Texas", "California", "D.C.", "Florida", "Texas", "California", "D.C." ))
alldata <- cbind(variablestouse, times, state)
newdata <- data.frame(alldata)
myanova <-aov(formula = as.numeric(as.character(times)) ~ variablestouse, data= newdata)
summary(myanova)
variablestouse1 <- c("Business Lisence", "Business Lisence", "Business Lisence","Massage Lisence", "Massage Lisence", "Massage Lisence", "Crimes", "Crimes", "Crimes")
times1 <- c( "2", "3", "4", "5", "5", "5", "12", "40", "20")
state1 <- (c("Texas", "California", "D.C.", "Texas", "California", "D.C.", "Texas", "California", "D.C." ))
alldata1 <- cbind(variablestouse1, times1, state1)
newdata1 <- data.frame(alldata1)
myanova1 <-aov(formula = as.numeric(as.character(times1)) ~ variablestouse1, data= newdata1)
summary(myanova1)
TukeyHSD(myanova1)
